FROM golang:1.12.0 AS builder
WORKDIR /go/src/github.com/se1exin/hue-im-home
COPY ./ .
RUN make build-go-arm

FROM arm32v7/alpine:latest
COPY qemu-arm-static /usr/bin
RUN apk add nmap
COPY --from=builder /go/src/github.com/se1exin/hue-im-home/hue-im-home_arm /hue-im-home
RUN chmod +x /hue-im-home && mkdir /config
ENTRYPOINT ["/hue-im-home"]